export const BASE_URL_API = window.REACT_APP_BASE_URL_API || ''
export const REACT_APP_BASIC_AUTH_USER = window.REACT_APP_BASIC_AUTH_USER || ''
export const REACT_APP_BASIC_AUTH_PASSWORD = window.REACT_APP_BASIC_AUTH_PASSWORD || ''