name: Docker Image CI

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker build services
        run: |
          docker build . -t auto1/test-data-storage-ui:latest -f ./Dockerfile

      - name: Login to DockerHub
        uses: auto1-oss/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker push
        run: |
          docker push auto1/test-data-storage-ui:latest

